default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: addis_baroque_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: addis_baroque_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
